### ISSUE TITLE
docker-plugins crashes with newer docker versions

### ISSUE THREAD

**Issue by tgeens** [progrium/docker-plugins#4]
Running docker version 1.10.3:

```
$ docker run --rm -it -v /var/run/docker.sock:/var/run/docker.sock progrium/plugins
Starting docker-plugins with:
  autoremove           1.0   disabled   Removes any container that dies, including stops and kills
  envhooks             1.0   disabled   Evaluates hook code from environ variables ENVHOOKS_<EVENT>
  timeout              1.0   disabled   Kills containers with TIMEOUT set after TIMEOUT seconds
  webhooks             1.0   disabled   Hits WEBHOOKS_URL or WEBHOOKS_<EVENT>_URL with a POST for each event
2016/03/16 22:26:14 info: trigger: a042f149e972 exists
2016/03/16 22:26:14 info: listening for Docker events...
```

In another terminal, I start a container:

```
$ docker run -it --rm tutum/hello-world
```

Back in the docker-plugins logs:

```
2016/03/16 22:26:16 info: trigger: 88aa5b3d987e create
2016/03/16 22:26:16 info: trigger: 88aa5b3d987e attach
panic: runtime error: slice bounds out of range

goroutine 35 [running]:
runtime.panic(0x719e80, 0x92360f)
    /usr/local/Cellar/go/1.3.3/libexec/src/pkg/runtime/panic.c:279 +0xf5
main.trigger(0xc20800e060, 0x2, 0x2, 0x0, 0x0, 0x0, 0x0, 0xc208010180)
    /Users/progrium/Projects/go/src/github.com/progrium/dockerhook/dockerhook.go:79 +0x856
created by main.main
    /Users/progrium/Projects/go/src/github.com/progrium/dockerhook/dockerhook.go:132 +0x74f
```

**Comment by tgeens** [comment]
This crash disappears if I rebuild `dockerhook` locally.

See issue https://github.com/progrium/dockerhook/issues/1
